
server:
  port: 8096
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.5.53:8848
        username: nacos
        password: nacos

#  redis:
#    host: localhost
#    port: 6379
#    password: root2023
#    database: 0
#    jedis:
#      pool:
#        max-active: 8 #最大连接数

  redis:
    host: 192.168.5.52
    port: 6379
    password: 123456
    database: 8
    jedis:
      pool:
        max-active: 8 #最大连接数





